# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy the entire application
#   See .azdo/pipelines/readme.me for details how to create the Playwright variable group and what it should contain
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: windows-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger: none
 
parameters:
  - name: createInfra
    displayName: Create Infra
    type: boolean
    default: true
  - name: buildDeployApps
    displayName: Build and Deploy Apps
    type: boolean
    default: true
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  - name: runGHAzDOScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runPlaywright
    displayName: Run Playwright Tests
    type: boolean
    default: false

# ------------------------------------------------------------------------------------------------------------------------
variables:
  - name: webSourcePath 
    value: 'services/Demo.WebUI'
  - name: apiSourcePath
    value:  'services/Demo.API'

  - name: webPackageName
    value:  'Demo.WebUI.zip'
  - name: apiPackageName
    value:  'Demo.API.zip'

  - name: webArtifactName
    value:  'WebApp'
  - name: apiArtifactName
    value:  'WebApi'

  - name: workingDirectoryCode
    value:  'services/'
  - name: workingDirectoryInfra
    value:  'infra/'
  
stages:
# ------------------------------------------------------------------------------------------------------------------------
  
- template: pipes/build-infra-deploy-pipe.yml
  parameters:
    variableGroupName: 'Playwright'

    createInfra: ${{ parameters.createInfra }}
    buildDeployApps: ${{ parameters.buildDeployApps }}
    runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
    runGHAzDOScan: ${{ parameters.runGHAzDOScan }}

    webSourcePath: ${{ variables.webSourcePath }}
    apiSourcePath: ${{ variables.apiSourcePath }}

    webPackageName: ${{ variables.webPackageName }}
    apiPackageName: ${{ variables.apiPackageName }}

    webArtifactName:  ${{ variables.webArtifactName }}
    apiArtifactName:  ${{ variables.apiArtifactName }}

    workingDirectoryCode: ${{ variables.workingDirectoryCode }}
    workingDirectoryInfra: ${{ variables.workingDirectoryInfra }}
