# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy the entire application (without needing a variable group)
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: windows-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger: none
 
parameters:
  - name: createInfra
    displayName: Create Infra
    type: boolean
    default: true
  - name: buildDeployApps
    displayName: Build and Deploy Apps
    type: boolean
    default: true
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  - name: runGHAzDOScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runPlaywright
    displayName: Run Playwright Tests
    type: boolean
    default: false

# ------------------------------------------------------------------------------------------------------------------------
variables:
  # variables that should be in a variable group...
  azureSubscription: 'Demo Account'
  apiAppName: 'rutzscodev-demo-webapp-api-auth-api-ci'
  apiAppAPIMName: 'rutzsco-demo-webapp-api-auth-api-ci'
  organizationName: 'scrutz'
  adminEmail: 'scrutz@microsoft.com'
  resourceGroupName: 'rutzscodev-demo-webapp-api-auth-api-ci'
  region: 'eastUS'
  adDomain: 'rutzscodev.onmicrosoft.com'
  adTenantId: '40b65298-615e-4102-b51c-260f15448b28'
  adClientId: 'addb1648-4905-4345-9fc2-5f74703d59ae'
  webAPIScope: 'api://b4d00308-29c0-463d-83c6-c457d18c281b/.default'
  webAPIUrl: 'https://rutzsco-demo-webapp-api-auth-api-ci2.azure-api.net/WeatherForecast'

  # Project Static variables
  webSourcePath: 'services/Demo.WebUI'
  apiSourcePath: 'services/Demo.API'
  webPackageName: 'Demo.WebUI.zip'
  apiPackageName: 'Demo.API.zip'
  webArtifactName: 'WebApp'
  apiArtifactName: 'WebApi'
  workingDirectoryCode: 'services/'
  workingDirectoryInfra: 'infra/'
  
stages:
# ------------------------------------------------------------------------------------------------------------------------
- template: pipes/build-infra-deploy-pipe.yml
  parameters:
    createInfra: ${{ parameters.createInfra }}
    buildDeployApps: ${{ parameters.buildDeployApps }}
    runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
    runGHAzDOScan: ${{ parameters.runGHAzDOScan }}

    organizationName:  ${{ variables.organizationName }}
    adminEmail:  ${{ variables.adminEmail }}
    resourceGroupName:  ${{ variables.resourceGroupName }}
    region: ${{ variables.region }}
    azureSubscription: ${{ variables.azureSubscription }}

    apiAppAPIMName:  ${{ variables.apiAppAPIMName }}
    webAPIScope: ${{ variables.webAPIScope }}
    webAPIUrl: ${{ variables.webAPIUrl }}

    webRootDirectory: ${{ variables.apiSourcePath }}
    apiRootDirectory: ${{ variables.apiSourcePath }}

    webAppName:  ${{ variables.webAppName }}
    apiAppName:  ${{ variables.apiAppName }}

    webPackageName: ${{ variables.webPackageName }}
    apiPackageName: ${{ variables.apiPackageName }}

    webSourcePath: ${{ variables.webSourcePath }}
    apiSourcePath: ${{ variables.apiSourcePath }}

    webArtifactName:  ${{ variables.webArtifactName }}
    apiArtifactName:  ${{ variables.apiArtifactName }}

    workingDirectoryCode: ${{ variables.workingDirectoryCode }}
    workingDirectoryInfra: ${{ variables.workingDirectoryInfra }}

    adDomain: ${{ variables.adDomain }}
    adTenantId: ${{ variables.adTenantId }}
    adClientId: ${{ variables.acClientId }}
