# ----------------------------------------------------------------------------------------------------
# Template to deploy Azure Resources for one environment
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: createInfra
  default: true
- name: stageName
  default: 'CI'
- name: environment
  default: 'CI'
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''
- name: apiAppName
  default: ''
- name: apiAppAPIMName
  default: ''
- name: organizationName
  default: ''
- name: adminEmail
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''
- name: templateFolderName
  default: 'infra\arm'
- name: bicepFolderName
  default: 'infra\bicep'
- name: adDomain
  default: ''
- name: adTenantId
  default: ''
- name: adClientId
  default: ''
- name: webAPIScope
  default: ''
- name: webAPIUrl
  default: ''

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: CreateInfra
  displayName: Create Infra
  environment: ${{ parameters.environment }}
- job: CreateInfraJob
  displayName: Create Infra Job
  variables:
    - name: templateDirectory
      value: '$(Pipeline.Workspace)\s\${{ parameters.templateFolderName }}'
    - name: bicepDirectory
      value: '$(Pipeline.Workspace)\s\${{ parameters.bicepFolderName }}'
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo "createInfra=${{ parameters.createInfra }}"
        echo "stageName=${{ parameters.stageName }}"
        echo "environment=${{ parameters.environment }}"
        echo "azureSubscription=${{ parameters.azureSubscription }}"
        echo "webAppName=${{ parameters.webAppName }}"
        echo "apiAppAPIMName=${{ parameters.apiAppAPIMName }}"
        echo "organizationName=${{ parameters.organizationName }}"
        echo "adminEmail=${{ parameters.adminEmail }}"
        echo "resourceGroupName=${{ parameters.resourceGroupName }}"
        echo "region=${{ parameters.region }}"
        echo "adDomain=${{ parameters.adDomain }}"
        echo "adTenantId=${{ parameters.adTenantId }}"
        echo "adClientId=${{ parameters.adClientId }}"
        echo "Directory Listing for: $(templateDirectory)"
        dir  $(templateDirectory) /s
        echo "Directory Listing for: $(bicepDirectory)"
        dir  $(bicepDirectory) /s
    displayName: 'Display Variables and Tree'
    continueOnError: true

  - ${{ if eq(lower(parameters.createInfra), 'true') }}:
    - task: AzureResourceGroupDeployment@2
      displayName: '1. Create APIM Consumption'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        resourceGroupName: ${{ parameters.resourceGroupName }}
        location: ${{ parameters.region }}
        csmFile: '$(templateDirectory)\api-management-consumption.json'
        overrideParameters: '-apimName ${{ parameters.apiAppAPIMName }}2 -organizationName ${{ parameters.organizationName }} -adminEmail ${{ parameters.adminEmail }}'
        deploymentOutputs: ResourceGroupDeploymentOutputs

    - task: AzureResourceGroupDeployment@2
      displayName: '2. Create APIM Dev'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        resourceGroupName: ${{ parameters.resourceGroupName }}
        location: ${{ parameters.region }}
        csmFile: '$(templateDirectory)\api-management-core.json'
        overrideParameters: '-serviceName ${{ parameters.apiAppAPIMName }}3 -publisherName ${{ parameters.organizationName }} -publisherEmail ${{ parameters.adminEmail }}'
        deploymentOutputs: ResourceGroupDeploymentOutputs

    - task: AzureResourceGroupDeployment@2
      displayName: '3. Create WebAPI Service'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        resourceGroupName: ${{ parameters.resourceGroupName }}
        location: ${{ parameters.region }}
        csmFile: '$(templateDirectory)\appservice-web-api.json'
        overrideParameters: '-appName ${{ parameters.apiAppName }}'
        deploymentOutputs: ResourceGroupDeploymentOutputs

    # - task: AzureResourceGroupDeployment@2
    #   displayName: '4. Create WebApp Service ARM'
    #   inputs:
    #     azureSubscription: ${{ parameters.azureSubscription }}
    #     resourceGroupName: ${{ parameters.resourceGroupName }}
    #     location: ${{ parameters.region }}
    #     csmFile: '$(templateDirectory)\appservice-web-app.json'
    #     overrideParameters: '-appName ${{ parameters.webAppName }}'
    #     deploymentOutputs: ResourceGroupDeploymentOutputs

    - task: AzureResourceGroupDeployment@2
      displayName: '4. Create WebApp Bicep'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        resourceGroupName: ${{ parameters.resourceGroupName }}
        location: ${{ parameters.region }}
        csmFile: '$(bicepDirectory)\main.bicep'
        overrideParameters: >
          -appName ${{ parameters.webAppName }} 
          -environmentCode ${{ parameters.environment }}
          -adDomain ${{ parameters.adDomain }}
          -adTenantId ${{ parameters.adTenantId }}
          -adClientId ${{ parameters.adClientId }}
          -location ${{ parameters.region }}
          -webAPIScope ${{ parameters.webAPIScope }}
          -webAPIUrl ${{ parameters.webAPIUrl }}
        deploymentOutputs: ResourceGroupDeploymentOutputs
