# ----------------------------------------------------------------------------------------------------
# Template to deploy Azure Resources for one environment
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: variableGroupName
  default: ''
- name: createInfra
  default: true
- name: environment
  default: 'CI'
- name: templateFolderName
  default: 'infra\arm'
- name: bicepFolderName
  default: 'infra\bicep'

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: CreateInfra
  displayName: Create Infra
  environment: ${{ parameters.environment }}
- job: CreateInfraJob
  displayName: Create Infra Job
  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: environmentNameUpper
      value: ${{ upper(parameters.environment) }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environment) }}
    - name: templateDirectory
      value: '$(Pipeline.Workspace)\s\${{ parameters.templateFolderName }}'
    - name: bicepDirectory
      value: '$(Pipeline.Workspace)\s\${{ parameters.bicepFolderName }}'
  steps:
  - bash: |
      runDateTime=$(echo $(date '+%Y%m%d-%H%M%S'))
      echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
      echo "runDateTime=$runDateTime"
      runDateTimeZ=$(echo $(date '+%Y%m%dT%H%M%SZ'))
      echo "##vso[task.setvariable variable=runDateTimeZ]$runDateTimeZ"
      echo "runDateTimeZ=$runDateTimeZ"
    displayName: 'Create Variables'
    continueOnError: true
  - task: CmdLine@2
    inputs:
      script: |
        echo "createInfra=${{ parameters.createInfra }}"
        echo "environment=${{ parameters.environment }}"

        echo "adminEmail=$(adminEmail)"
        echo "adDomain=$(adDomain)"
        echo "adTenantId=$(adTenantId)"
        echo "adClientId=$(adClientId)"
        echo "apiAppName=$(apiAppName)"
        echo "apiAppAPIMName=$(apiAppAPIMName)"
        echo "azureSubscription=$(azureSubscription)"
        echo "organizationName=$(organizationName)"
        echo "resourceGroupName=$(resourceGroupName)"
        echo "region=$(region)"
        echo "webAPIScope=$(webAPIScope)"
        echo "webAPIUrl=$(webAPIUrl)"
        echo "webAppName=$(webAppName)"
        echo "Bicep Deploy Sample Command:"
        echo "  az deployment group create -n main-deploy-$(runDateTimeZ) --resource-group $(resourceGroupName) --template-file 'main.bicep' --parameters appName $(webAppName) environmentCode $(environmentNameLower) adDomain $(adDomain) adTenantId $(adTenantId) adClientId $(adClientId) location $(region) webAPIScope $(webAPIScope) webAPIUrl $(webAPIUrl)"
        echo "Directory Listing for: $(templateDirectory)"
        dir  $(templateDirectory) /s
        echo "Directory Listing for: $(bicepDirectory)"
        dir  $(bicepDirectory) /s
        type $(bicepDirectory)\main.bicep
    displayName: 'Display Variables and Tree'
    continueOnError: true

  - ${{ if eq(lower(parameters.createInfra), 'true') }}:
    - task: AzureResourceGroupDeployment@2
      displayName: '1. Create APIM Consumption'
      inputs:
        azureSubscription: $(azureSubscription)
        resourceGroupName: $(resourceGroupName)
        location: $(region)
        csmFile: '$(templateDirectory)\api-management-consumption.json'
        overrideParameters: '-apimName $(apiAppAPIMName)2 -organizationName $($)organizationName) -adminEmail $(adminEmail)'
        deploymentOutputs: ResourceGroupDeploymentOutputs

    - task: AzureResourceGroupDeployment@2
      displayName: '2. Create APIM Dev'
      inputs:
        azureSubscription: $(azureSubscription)
        resourceGroupName: $(resourceGroupName)
        location: $(region)
        csmFile: '$(templateDirectory)\api-management-core.json'
        overrideParameters: '-serviceName $(apiAppAPIMName)3 -publisherName $(organizationName) -publisherEmail $(adminEmail)'
        deploymentOutputs: ResourceGroupDeploymentOutputs

    - task: AzureResourceGroupDeployment@2
      displayName: '3. Create WebAPI Service'
      inputs:
        azureSubscription: $(azureSubscription)
        resourceGroupName: $(resourceGroupName)
        location: $(region)
        csmFile: '$(templateDirectory)\appservice-web-api.json'
        overrideParameters: '-appName $(apiAppName)'
        deploymentOutputs: ResourceGroupDeploymentOutputs

    # - task: AzureResourceGroupDeployment@2
    #   displayName: '4. Create WebApp Service ARM'
    #   inputs:
    #     azureSubscription: ${{ parameters.azureSubscription)
    #     resourceGroupName: ${{ parameters.resourceGroupName)
    #     location: ${{ parameters.region)
    #     csmFile: '$(templateDirectory)\appservice-web-app.json'
    #     overrideParameters: '-appName ${{ parameters.webAppName)'
    #     deploymentOutputs: ResourceGroupDeploymentOutputs

    - task: AzureResourceGroupDeployment@2
      displayName: '4. Create WebApp Bicep'
      inputs:
        csmFile: $(bicepDirectory)\main.bicep
        overrideParameters: >
          -appName $(webAppName)
          -environmentCode $(environmentNameLower)
          -adDomain $(adDomain)
          -adTenantId $(adTenantId)
          -adClientId $(adClientId)
          -location $(region)
          -webAPIScope $(webAPIScope)
          -webAPIUrl $(webAPIUrl)
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureSubscription)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(region)'
        templateLocation: 'Linked artifact'
        deploymentMode: 'Incremental'
