# ----------------------------------------------------------------------------------------------------
# Template to deploy the WebAPI and WebApp to Azure
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: buildDeployApps
  default: true
- name: stageName
  default: 'CI'
- name: environment
  default: 'CI'
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''
- name: webPackageName
  default: ''  
- name: apiAppName
  default: ''
- name: apiPackageName
  default: ''  
- name: apiArtifactName
  default: ''  
- name: webArtifactName
  default: ''  

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: DeployApps
  displayName: Deploy Apps
  environment: ${{ parameters.environment }}

- job: DeployAppsJob
  displayName: Deploy Apps Job
  steps:
  - ${{ if eq(lower(parameters.buildDeployApps), 'true') }}:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download WebApi Artifact'
      inputs:
        artifact: ${{ parameters.apiArtifactName }}
        targetPath: '$(Pipeline.Workspace)\WebApi' 

    - task: DownloadPipelineArtifact@2
      displayName: 'Download WebApp Artifact'
      inputs:
        artifact: ${{ parameters.webArtifactName }}
        targetPath: '$(Pipeline.Workspace)\WebApp' 

  - task: CmdLine@2
    inputs:
      script: |
        echo "stageName=${{ parameters.stageName }}"
        echo "environment=${{ parameters.environment }}"
        echo "azureSubscription=${{ parameters.azureSubscription }}"
        echo "webAppName=${{ parameters.webAppName }}"
        echo "webPackageName=${{ parameters.webPackageName }}"
        echo "apiAppName=${{ parameters.apiAppName }}"
        echo "apiPackageName=${{ parameters.apiPackageName }}"
        echo "apiArtifactName=${{ parameters.apiArtifactName }}"
        echo "webArtifactName=${{ parameters.webArtifactName }}"
        echo "Directory of Pipeline.Workspace:"
        dir  $(Pipeline.Workspace) /s
    displayName: 'Display Variables and Tree'
    continueOnError: true

  - ${{ if eq(lower(parameters.buildDeployApps), 'true') }}:
    - task: AzureRmWebAppDeployment@4
      displayName: '1. Deploy API'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        WebAppName: ${{ parameters.apiAppName }}
        package: '$(Pipeline.Workspace)\WebApi\*.zip'
        AppSettings: ''

    - task: AzureRmWebAppDeployment@4
      displayName: '2. Deploy WebApp'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        WebAppName: ${{ parameters.webAppName }}
        package: '$(Pipeline.Workspace)\WebApp\*.zip'
        AppSettings: ''