# ------------------------------------------------------------------------------------------------------------------------
# Pipe Template to build and deploy the entire application
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: createInfra
  default: true
- name: buildDeployApps
  default: true
- name: buildConfiguration
  default: 'Release'
- name: azureSubscription
  default: ''
- name: organizationName
  default: ''
- name: adminEmail
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''

- name: apiAppAPIMName
  default: ''

- name: webAppName
  default: ''
- name: apiAppName
  default: ''

- name: webPackageName
  default: ''
- name: apiPackageName
  default: ''

- name: webSourcePath
  default: ''
- name: apiSourcePath
  default: ''

- name: webArtifactName
  default: ''
- name: apiArtifactName
  default: ''

- name: runDevSecOpsScan
  default: 'false'
- name: runPsRuleScan
  default: 'false'
- name: runGHAzDOScan
  default: 'false'
- name: workingDirectoryCode
  default: 'src/myproject'
- name: workingDirectoryInfra
  default: '/infra/bicep'

- name: adDomain
  default: ''
- name: adTenantId
  default: ''
- name: adClientId
  default: ''
- name: webAPIScope
  default: ''
- name: webAPIUrl
  default: ''

stages:
# ------------------------------------------------------------------------------------------------------------------------
- stage: BuildApps
  displayName: Build Apps (${{ parameters.buildDeployApps }})
  jobs:

  - ${{ if or(or(eq(lower(parameters.runDevSecOpsScan), 'true'), eq(lower(parameters.runPsRuleScan), 'true')), eq(lower(parameters.runGHAzDOScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
        runPsRuleScan: ${{ parameters.runPsRuleScan }}
        runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
        workingDirectoryCode: ${{ parameters.workingDirectoryCode }}
        workingDirectoryInfra: ${{ parameters.workingDirectoryInfra }}

  - template: templates/build-webapi-template.yml
    parameters:
      buildDeployApps: ${{ parameters.buildDeployApps }}
      buildConfiguration: 'Release'
      rootDirectory: ${{ parameters.apiSourcePath }}
      artifactName: ${{ parameters.apiArtifactName }} 

  - template: templates/build-webapp-template.yml
    parameters:
      buildDeployApps: ${{ parameters.buildDeployApps }}
      buildConfiguration: 'Release'
      rootDirectory: ${{ parameters.webSourcePath }}
      artifactName: ${{ parameters.webArtifactName }}

# ------------------------------------------------------------------------------------------------------------------------
- stage: CreateAzureInfra
  displayName: Create Infra (${{ parameters.createInfra }})
  dependsOn: BuildApps
  condition: succeeded('BuildApps')
  jobs:
  - template: templates/create-infra-template.yml
    parameters:
      createInfra: ${{ parameters.createInfra }}
      azureSubscription: ${{ parameters.azureSubscription }}
      webAppName:  ${{ parameters.webAppName }}
      apiAppName:  ${{ parameters.apiAppName }}
      apiAppAPIMName:  ${{ parameters.apiAppAPIMName }}
      organizationName:  ${{ parameters.organizationName }}
      adminEmail:  ${{ parameters.adminEmail }}
      resourceGroupName:  ${{ parameters.resourceGroupName }}
      region: ${{ parameters.region }}
      adDomain:  ${{ parameters.adDomain }}
      adTenantId:  ${{ parameters.adTenantId }}
      adClientId:  ${{ parameters.adClientId }}
      webAPIScope:  ${{ parameters.webAPIScope }}
      webAPIUrl:  ${{ parameters.webAPIUrl }}

# ------------------------------------------------------------------------------------------------------------------------
- stage: DeployApp
  displayName: Deploy App (${{ parameters.buildDeployApps }})
  dependsOn: CreateAzureInfra
  condition: succeeded('CreateAzureInfra')
  jobs:
  - template: templates/deploy-apps-template.yml
    parameters:
      buildDeployApps: ${{ parameters.buildDeployApps }}
      azureSubscription: ${{ parameters.azureSubscription }}
      webAppName:  ${{ parameters.webAppName }}
      apiAppName:  ${{ parameters.apiAppName }}
      webPackageName: ${{ parameters.webPackageName }}
      apiPackageName: ${{ parameters.apiPackageName }}
      webArtifactName: ${{ parameters.webArtifactName }}
      apiArtifactName: ${{ parameters.apiArtifactName }} 
