parameters: 
- name: stageName
  default: 'CI'
- name: environment
  default: 'CI'
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''
- name: webAppPackageName
  default: ''  
- name: apiAppName
  default: ''
- name: apiPackageName
  default: ''  


stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'windows-latest'
  
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureRmWebAppDeployment@4
              displayName: '1. Deploy API'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                WebAppName: ${{ parameters.apiAppName }}
                package: '$(Pipeline.Workspace)/build/App/${{ parameters.apiPackageName }}'
                AppSettings: ''

            - task: AzureRmWebAppDeployment@4
              displayName: '2. Deploy WebApp'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                WebAppName: ${{ parameters.webAppName }}
                package: '$(Pipeline.Workspace)/build/App/${{ parameters.webAppPackageName }}'
                AppSettings: ''