parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''
- name: resourceGroupName
  default: ''
- name: storageAccountName
  default: ''
- name: region
  default: ''
- name: packageName
  default: ''  


stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'vs2017-win2016'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureResourceGroupDeployment@2
              displayName: '1. Create App Service'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.region }}
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/appservice-web-app.json'
                overrideParameters: '-appName ${{ parameters.webAppName }}'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - task: AzureRmWebAppDeployment@4
              displayName: '3. Azure App Service Deploy:'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                WebAppName: ${{ parameters.webAppName }}
                package: '$(Pipeline.Workspace)/build/App/${{ parameters.packageName }}'
                AppSettings: ''